name: speed_reader
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

scripts:
  # run is a default script. To use it, simply type
  # in the command line: "rps" - that's all!
  get: "./scripts/clean/pubspec.sh"
  run:
    dev: "./scripts/run/dev.sh"
    prod: "./scripts/run/prod.sh"
  # you can define more commands like this: "rps gen"
  gen: "./scripts/utils/build_runner.sh"
  # rps appstore android
  build:
    android: "./scripts/build/android.sh"
    ios: "./scripts/build/ios.sh"
  release:
    android: "./scripts/release/playstore.sh"
    ios: "./scripts/release/appstore.sh"
    all: "./scripts/release/all.sh"
  clean:
    pubspec: "./scripts/clean/pubspec.sh"
    android: "./scripts/clean/android.sh"
    ios: "./scripts/clean/ios.sh"
    complete: "./scripts/clean/complete.sh"


dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_widget_from_html: ^0.15.1
  lucide_icons: ^0.257.0
  font_awesome_flutter: ^10.7.0
  cupertino_modal_sheet: ^1.1.0
  freezed: ^2.5.4
  freezed_annotation: ^2.4.2
  json_serializable: ^6.8.0
  path_provider: ^2.1.3
  #state management
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5



dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.11
dependency_overrides:
  analyzer: ^6.5.0
  meta: ^1.15.0
flutter:
  uses-material-design: true
  generate: true
